### ISSUE TITLE
TASK_HEADER_KEY, FLUX_HEADER_KEY, FLUX_CREATE_URL

### ISSUE THREAD

**Issue by caiorangel** [virgoone/next-money#6]
I'm trying to set up the project but I'm having trouble understanding how to fill out the following environment variables: TASK_HEADER_KEY, FLUX_HEADER_KEY, and FLUX_CREATE_URL. I couldn't find any detailed explanation about them in the documentation.

Could you please provide more information about what these variables are, where I can find the required values, or any example on how to configure them correctly?

Thank you very much for your help!

**Comment by akshaynstack** [comment]
FLUX_CREATE_URL is serverless endpoint hosted somewhere else and used in this project

**Comment by virgoone** [comment]
yes, This is another service, which is not open-source for the time being.

AKSHAY N ***@***.***> 于2024年11月4日周一 04:07写道：

**Comment by akshaynstack** [comment]
Hi virgoone, We can use third party API from fal ai ? and work around ?

**Comment by virgoone** [comment]
Sure, you can access the third-party API yourself, or you can buy our
deployment service.

**Comment by akshaynstack** [comment]
How to buy your api ? please share link

**Comment by virgoone** [comment]
@akshaynstack What functions do you need? We also provide custom services for generating pictures, or just fluxaipro.art all the above functions, we can also provide custom development

**Comment by akshaynstack** [comment]
I need endpoints for flux models to generate images
